name: advanced_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_flutter_extensions: 1.2.0
  cupertino_icons: ^1.0.2
  dartx: 1.2.0
  flutter_cache_manager: 3.3.2
  http: 1.2.1
  rxdart: 0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  network_image_mock: 2.1.1

flutter:
  uses-material-design: true
